# Generated by Django 3.2.3 on 2021-05-25 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisional_name', models.CharField(max_length=250)),
                ('divisional_code', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('it_employee', models.BooleanField(default=False)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.division')),
            ],
        ),
    ]
