# Generated by Django 3.2.3 on 2021-05-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['-divisional_name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-user_name'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='division',
            name='divisional_code',
            field=models.CharField(max_length=250, verbose_name='Код отдела'),
        ),
        migrations.AlterField(
            model_name='division',
            name='divisional_name',
            field=models.CharField(max_length=250, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='department.division', verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='user',
            name='it_employee',
            field=models.BooleanField(default=False, verbose_name='Является сотрудником'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=250, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус (активен/неактивен)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=250, verbose_name='Имя пользователя'),
        ),
    ]
